version: '3'
services:
  ninemanga:
    build:
      context: .
    container_name: ninemanga.app
    volumes:
      # Here we mount in our codebase so any changes are immediately reflected into the container
      - '.:/python-docker'
    networks:
      - ninemanga
    entrypoint: python cli.py
    # entrypoint: /bin/sh
    stdin_open: true
    tty: true

networks:
  ninemanga:
